# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a56e1dac69ca74ad006ef2b99ba750d429e9614ca4082fe85fb419b515dfcea1018be7b072f72d9e2ea00c89f91f6e5ddd8f2bd5e05b47a2945c03b6f2647e6
  AUTH_SECRET: \x85\x11\xFA\xEF\xF2A\x11\xC7\x90\x9C!{\xDC\x11W\xFB\x93\xE5\xA3\xCD\xE3\xC2\x9E#7\xC4\xCDa\xCF\xC9/\xEA

test:
  secret_key_base: 2323b5e3391dc8909d3eb03a764d24c2c9c50938c9e59806bc5b6a90f8601c2cb8e99d32be1de27438830817d0048f73b14615b2dac6fe7ba90e36f4000141b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
